package:
  name: xgeoml
  version: "0.1.6"

source:
  git_url: https://github.com/UrbanGISer/XGeoML.git
  git_tag: v0.1.6
  path: XGeoML_Conda

build:
  number: 0
  script: python -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - scikit-learn
    - numpy
    - scipy
    - joblib
    - pandas
    - lime
    - shap
    - tqdm

about:
  home: https://github.com/UrbanGISer/XGeoML
  license: MIT
  summary: A ensemble framework for explainable geospatial machine Learning models
